add restaurant feature
kunmi02/restaurant-page pull request #1
Opened 2021-03-31 09:30 UTC by kunmi02

This project is to show my skills in javascript using webpack.

I set up and configured webpack.
I added images and also used object-oriented concept in the project

2021-03-31 10:24 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @kunmi02  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement all of the minimal requirements of this project, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] To make your project more professional, you need to make sure that all of the info presented on the readme file are accurate, please read and fix all of inline comments I put on your readme file

# [Optional changes] :yellow_circle: 
- [ ] It will be very nice if you try to add some styling on your restaurant page
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-03-31 10:24 UTC, descholar-ceo commented on README.md
> + http://akinkunmi.me/restaurant-page/
[required] This live demo link doesn't reach to the real live demo of your restaurant page, it showing your readme file instead, could you fix that issue?

2021-03-31 10:24 UTC, descholar-ceo commented on README.md
> +- Run index.html in your Web Browser.
[required] This file `index.html` is not found on the root directory of your project, you should specify where to find it

2021-03-31 10:24 UTC, descholar-ceo commented on README.md
> +
[required] All of the above steps needs clarification on the commands to use inorder to be able to performed any given action. You should not leave any room for assumption. Think of non-tech users who will need to test your app,

2021-03-31 12:25 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Azeez Azeez** 
Nice job with the improvements for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [ ] The package "webpack-dev-server" should be included in your package.json
- [ ] Necessary run commands should be in package.json, inside scripts:
`
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  }
`

- [ ] Add some styling for each tab

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/tab_requirement.png)
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2021-03-31 14:20 UTC, rindrajosia requested changes
Changes Required :red_circle:
To Highlight: :angel:

- [ ] I see that you are trying to work on tse's recommendation :muscle: 

To Improve :factory_worker: (REQUIRED)

- [ ] Some of your run commands don't perform as expected e.g. when I run the `npm start` command, I got some errors:
![1](https://user-images.githubusercontent.com/58552748/113158494-81ea9d00-9244-11eb-9949-c39ecbfe8f02.gif)

- [ ] All necessarily used packages should be included in package.json like `webpack`, `webpack-cli, webpack-dev-serve`r etc. Also, those packages **should be only added** as `devDependencies` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/devdep_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/))
- [ ] Please, add styling to your webpage as it is part of project requirement.

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

2021-04-02 12:24 UTC, oloomoses approved these changes
# Congratulations, Project Approved. :muscle: :tada: :clap: 
**Great job working on the suggested changes from the previous review.
You have passed all the requirements for this project :muscle: 
Feel free to merge and close this pull request.**

**I wish you the best in your next project and see you at the top :rocket:** 
#### Happy Coding
_Slack: Oloo Moses_

2021-04-02 12:41 UTC, merged